-- Refresh tokens (fase 0 de auth): o access token (JWT) agora vive pouco
-- (ver jwt.expiration-ms) e este token opaco, de vida mais longa, é trocado
-- por um par novo de access+refresh via POST /v1/auth/refresh -- ver
-- RefreshTokenService. Guardamos o hash (SHA-256), nunca o valor em si, e
-- cada refresh ROTACIONA o token (marca o antigo como revogado e emite um
-- novo), então um valor roubado só é reutilizável uma vez antes de virar
-- inválido em ambas as pontas.
CREATE TABLE t_refresh_token (
    id_refresh_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    tx_token_hash VARCHAR(64) NOT NULL UNIQUE,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_expiracao TIMESTAMP NOT NULL,
    dt_revogacao TIMESTAMP
);

CREATE INDEX idx_refresh_token_usuario ON t_refresh_token(usuario_id);
