-- Log de acesso/ações a nível de documento (quem viu, quem editou, quando --
-- ver LogAuditoriaService). documento_id/documento_descricao são um
-- snapshot no momento da ação, sem FK para t_documento: o documento pode
-- ser excluído mais tarde (ver DocumentoAcessoService.podeExcluir) e a
-- trilha de auditoria precisa sobreviver a isso.
CREATE TABLE t_log_auditoria (
    id_log_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario),
    documento_id BIGINT NOT NULL,
    documento_descricao VARCHAR(255) NOT NULL,
    sg_acao VARCHAR(30) NOT NULL,
    tx_detalhe VARCHAR(500),
    dt_ocorrencia TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_log_auditoria_documento ON t_log_auditoria(documento_id);
CREATE INDEX idx_log_auditoria_usuario ON t_log_auditoria(usuario_id);
CREATE INDEX idx_log_auditoria_dt_ocorrencia ON t_log_auditoria(dt_ocorrencia);

-- Papel AUDITOR (ver PapelEnum) -- sg_papel já é VARCHAR livre em
-- t_usuario_papel (sem CHECK constraint), então nenhuma alteração de
-- schema é necessária para o novo valor do enum além deste comentário.
