-- Notificação real (ver NotificacaoService): gravada na mesma transação da
-- ação que a gera (compartilhamento, documento entrando em situação que
-- pede aprovação) e entregue ao vivo por SSE quando o destinatário está
-- conectado (NotificacaoEmitterRegistry) -- esta tabela é sempre a fonte
-- de verdade, então também cobre quem estava offline no momento do evento.
CREATE TABLE t_notificacao (
    id_notificacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    sg_tipo VARCHAR(30) NOT NULL,
    tx_mensagem VARCHAR(500) NOT NULL,
    documento_id BIGINT NOT NULL,
    documento_descricao VARCHAR(255) NOT NULL,
    fl_lida BOOLEAN NOT NULL DEFAULT false,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_leitura TIMESTAMP
);

CREATE INDEX idx_notificacao_destinatario ON t_notificacao(destinatario_id, fl_lida);
