-- Postos (oficiais) e graduações (praças) da FAB -- ver PostoGraduacao.java.
-- bigrama é o código de exibição compacta; ordem reflete a hierarquia
-- militar (menor = mais alto), não ordem alfabética.
CREATE TABLE t_posto_graduacao (
    id_posto_graduacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_posto_graduacao VARCHAR(60) NOT NULL,
    sg_bigrama VARCHAR(4) NOT NULL UNIQUE,
    nr_ordem INTEGER NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_alteracao TIMESTAMP,
    nr_versao INTEGER NOT NULL DEFAULT 0
);

INSERT INTO t_posto_graduacao (nm_posto_graduacao, sg_bigrama, nr_ordem) VALUES
    ('Marechal-do-Ar',           'MA', 10),
    ('Tenente-Brigadeiro do Ar', 'TB', 20),
    ('Major-Brigadeiro do Ar',   'MB', 30),
    ('Brigadeiro do Ar',         'BR', 40),
    ('Coronel',                  'CL', 50),
    ('Tenente-Coronel',          'TC', 60),
    ('Major',                    'MJ', 70),
    ('Capitão',                  'CP', 80),
    ('Primeiro-Tenente',         '1T', 90),
    ('Segundo-Tenente',          '2T', 100),
    ('Aspirante-a-Oficial',      'AP', 110),
    ('Suboficial',               'SO', 120),
    ('Primeiro-Sargento',        '1S', 130),
    ('Segundo-Sargento',         '2S', 140),
    ('Terceiro-Sargento',        '3S', 150),
    ('Taifeiro-Mor',             'TF', 160),
    ('Cabo',                     'CB', 170),
    ('Soldado',                  'SD', 180);

-- Perfil do usuário: posto/graduação (nullable -- nem todo usuário do
-- sistema é militar, ex.: servidor civil), nome de guerra e e-mail.
ALTER TABLE t_usuario ADD COLUMN posto_graduacao_id BIGINT REFERENCES t_posto_graduacao(id_posto_graduacao);
ALTER TABLE t_usuario ADD COLUMN tx_nome_guerra VARCHAR(60);
ALTER TABLE t_usuario ADD COLUMN tx_email VARCHAR(150);
