-- Desfaz a concatenacao da portaria com o PDF do documento (V16): mesclar um
-- PDF de portaria assinado digitalmente no futuro invalidaria a assinatura,
-- que cobre um intervalo de bytes exato do arquivo original. Cada portaria
-- do ciclo de vida do documento (edicao, alteracoes sucessivas, revogacao)
-- passa a ser um registro proprio, com o PDF preservado intacto.
ALTER TABLE t_documento DROP COLUMN tx_url_portaria_pdf;

-- Nome deliberadamente diferente de t_portaria, que ja e a tabela de
-- ItemPartePreliminar (ver V1__initial.sql).
CREATE TABLE t_portaria_publicacao (
    id_portaria_publicacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento(id_documento),
    sg_tipo VARCHAR(20) NOT NULL,       -- EDICAO | ALTERACAO | REVOGACAO
    nr_sequencial INTEGER,               -- so para ALTERACAO (1, 2, 3...)
    tx_orgao VARCHAR(60) NOT NULL,
    tx_setor VARCHAR(60),
    tx_numero_portaria VARCHAR(30) NOT NULL,
    dt_portaria DATE NOT NULL,
    nr_bca INTEGER NOT NULL,
    dt_bca DATE NOT NULL,
    url_pdf VARCHAR(500) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_portaria_publicacao_documento_id ON t_portaria_publicacao(documento_id);
