-- Schema inicial consolidado (o sistema ainda não entrou em produção, então todo o
-- histórico de migrations anteriores foi agrupado numa única versão).
--
-- Observação importante: nenhuma coluna baseada em enum Java (status, tipo de item,
-- tipo de emenda etc.) tem CHECK CONSTRAINT no banco. O Hibernate costuma gerar essas
-- constraints automaticamente a partir dos valores do enum na primeira vez que a
-- tabela é criada, e elas ficam desatualizadas (e passam a rejeitar gravações válidas)
-- sempre que o enum ganha um novo valor. A validação desses valores já é feita pela
-- camada de aplicação via @Enumerated(EnumType.STRING); o banco só armazena o texto.

-- ── Tabelas de referência (sem dependências) ─────────────────────────────────

CREATE TABLE t_especie_normativa (
    id_especie_normativa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sg_especie_normativa VARCHAR(255) NOT NULL,
    nm_especie_normativa VARCHAR(255) NOT NULL,
    tx_descricao          TEXT NOT NULL,
    dt_criacao            TIMESTAMP,
    dt_alteracao           TIMESTAMP,
    nr_versao              INTEGER NOT NULL
);

CREATE TABLE t_assunto_basico (
    id_assunto_basico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_assunto_basico VARCHAR(4) NOT NULL,
    tx_descricao       TEXT NOT NULL,
    nm_classificacao   VARCHAR(255) NOT NULL,
    dt_criacao         TIMESTAMP,
    dt_alteracao       TIMESTAMP,
    nr_versao          INTEGER NOT NULL
);

-- ── Documento e histórico ─────────────────────────────────────────────────────

CREATE TABLE t_documento (
    id_documento           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    especie_normativa_id   BIGINT NOT NULL REFERENCES t_especie_normativa (id_especie_normativa),
    assunto_basico_id      BIGINT NOT NULL REFERENCES t_assunto_basico (id_assunto_basico),
    nr_numero_secundario   INTEGER NOT NULL,
    nm_titulo_documento    VARCHAR(255) NOT NULL,
    st_documento           VARCHAR(30) NOT NULL,
    dt_criacao             TIMESTAMP,
    dt_alteracao           TIMESTAMP,
    dt_minuta              TIMESTAMP,
    dt_aprovacao           TIMESTAMP,
    dt_publicacao          TIMESTAMP,
    dt_arquivamento        TIMESTAMP,
    dt_revogacao           TIMESTAMP,
    dt_cancelamento        TIMESTAMP,
    dt_em_alteracao        TIMESTAMP,
    url_pdf                VARCHAR(255),
    nr_replicas            INTEGER NOT NULL DEFAULT 0,
    tx_portaria_referencia VARCHAR(255),
    tx_bca_referencia      VARCHAR(255),
    nr_versao              INTEGER NOT NULL
);

CREATE TABLE t_historico_documento (
    id_historico        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id        BIGINT NOT NULL REFERENCES t_documento (id_documento),
    tx_descricao        VARCHAR(255) NOT NULL,
    sg_tipo_alteracao   VARCHAR(30) NOT NULL,
    sg_status_anterior  VARCHAR(30),
    sg_status_novo      VARCHAR(30),
    nm_usuario          VARCHAR(255),
    dt_registro         TIMESTAMP
);

CREATE TABLE t_emenda_historico (
    id_emenda            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id         BIGINT NOT NULL,
    secao                VARCHAR(30) NOT NULL,
    elemento_id          BIGINT NOT NULL,
    acao                 VARCHAR(20) NOT NULL,
    tx_conteudo_anterior TEXT,
    tx_conteudo_novo     TEXT,
    tx_titulo_anterior   VARCHAR(255),
    tx_titulo_novo       VARCHAR(255),
    tx_justificativa     TEXT,
    dt_emenda            TIMESTAMP
);

-- ── Anexos ─────────────────────────────────────────────────────────────────

CREATE TABLE t_anexo (
    id_anexo     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento (id_documento),
    nr_ordem     INTEGER NOT NULL,
    tx_titulo    VARCHAR(255) NOT NULL,
    url_imagem   VARCHAR(255) NOT NULL,
    dt_criacao   TIMESTAMP
);

-- ── Itens do documento (preliminar, normativa, final) ────────────────────────
-- As três tabelas compartilham a mesma forma (herdada de um mesmo conceito de
-- "item de conteúdo"); t_item_parte_normativa é a única com auto-referência
-- (parent_id) para representar a árvore de capítulos/seções/artigos/etc.

CREATE TABLE t_portaria (
    id_portaria             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            BIGINT NOT NULL REFERENCES t_documento (id_documento),
    sg_tipo_item            VARCHAR(255) NOT NULL,
    nr_ordem                INTEGER,
    tx_titulo_item          TEXT,
    tx_conteudo_item        TEXT,
    tx_conteudo_completo    TEXT,
    st_emenda               VARCHAR(20),
    tx_conteudo_original    TEXT,
    tx_titulo_original      TEXT,
    tx_conteudo_emenda      TEXT,
    tx_titulo_emenda        TEXT,
    tx_justificativa_emenda TEXT,
    dt_criacao              TIMESTAMP,
    dt_atualizacao          TIMESTAMP
);

CREATE TABLE t_item_parte_normativa (
    id_item                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            BIGINT NOT NULL REFERENCES t_documento (id_documento),
    parent_id               BIGINT REFERENCES t_item_parte_normativa (id_item),
    sg_tipo_item            VARCHAR(255) NOT NULL,
    nr_ordem                INTEGER,
    tx_titulo_item          TEXT,
    tx_conteudo_item        TEXT,
    tx_conteudo_completo    TEXT,
    st_emenda               VARCHAR(20),
    tx_conteudo_original    TEXT,
    tx_titulo_original      TEXT,
    tx_conteudo_emenda      TEXT,
    tx_titulo_emenda        TEXT,
    tx_justificativa_emenda TEXT,
    dt_criacao              TIMESTAMP,
    dt_atualizacao          TIMESTAMP
);

CREATE TABLE t_item_parte_final (
    id_item                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            BIGINT NOT NULL REFERENCES t_documento (id_documento),
    sg_tipo_item            VARCHAR(255) NOT NULL,
    nr_ordem                INTEGER,
    tx_titulo_item          TEXT,
    tx_conteudo_item        TEXT,
    tx_conteudo_completo    TEXT,
    st_emenda               VARCHAR(20),
    tx_conteudo_original    TEXT,
    tx_titulo_original      TEXT,
    tx_conteudo_emenda      TEXT,
    tx_titulo_emenda        TEXT,
    tx_justificativa_emenda TEXT,
    dt_criacao              TIMESTAMP,
    dt_atualizacao          TIMESTAMP
);
