-- Schema inicial consolidado (o sistema ainda não entrou em produção, então todo o
-- histórico de migrations anteriores foi agrupado numa única versão — segunda vez que
-- isso acontece; a V1 antiga já era, ela mesma, uma consolidação de um histórico
-- anterior, e V2-V22 se acumularam por cima dela desde então).
--
-- Observação importante: nenhuma coluna baseada em enum Java (status, tipo de item,
-- tipo de emenda etc.) tem CHECK CONSTRAINT no banco. O Hibernate costuma gerar essas
-- constraints automaticamente a partir dos valores do enum na primeira vez que a
-- tabela é criada, e elas ficam desatualizadas (e passam a rejeitar gravações válidas)
-- sempre que o enum ganha um novo valor. A validação desses valores já é feita pela
-- camada de aplicação via @Enumerated(EnumType.STRING); o banco só armazena o texto.

-- ── Tabelas de referência (sem dependências) ─────────────────────────────────

CREATE TABLE t_especie_normativa (
    id_especie_normativa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sg_especie_normativa VARCHAR(255) NOT NULL,
    nm_especie_normativa VARCHAR(255) NOT NULL,
    tx_descricao          TEXT NOT NULL,
    dt_criacao            TIMESTAMP,
    dt_alteracao           TIMESTAMP,
    nr_versao              INTEGER NOT NULL
);

CREATE TABLE t_assunto_basico (
    id_assunto_basico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_assunto_basico VARCHAR(4) NOT NULL,
    tx_descricao       TEXT NOT NULL,
    nm_classificacao   VARCHAR(255) NOT NULL,
    dt_criacao         TIMESTAMP,
    dt_alteracao       TIMESTAMP,
    nr_versao          INTEGER NOT NULL
);

-- Postos (oficiais) e graduações (praças) da FAB -- ver PostoGraduacao.java.
-- bigrama é o código de exibição compacta; precedencia reflete a hierarquia
-- militar (menor = mais alto), não ordem alfabética. Nome deliberadamente
-- diferente de "nr_ordem" -- nos bancos internos da FAB esse termo já
-- designa a matrícula do militar, não uma posição em lista.
CREATE TABLE t_posto_graduacao (
    id_posto_graduacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_posto_graduacao VARCHAR(60) NOT NULL,
    sg_bigrama VARCHAR(4) NOT NULL UNIQUE,
    nr_precedencia INTEGER NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_alteracao TIMESTAMP,
    nr_versao INTEGER NOT NULL DEFAULT 0
);

INSERT INTO t_posto_graduacao (nm_posto_graduacao, sg_bigrama, nr_precedencia) VALUES
    ('Marechal-do-Ar',              'MA', 10),
    ('Tenente-Brigadeiro do Ar',    'TB', 20),
    ('Major-Brigadeiro do Ar',      'MB', 30),
    ('Brigadeiro do Ar',            'BR', 40),
    ('Coronel',                     'CL', 50),
    ('Tenente-Coronel',             'TC', 60),
    ('Major',                       'MJ', 70),
    ('Capitão',                     'CP', 80),
    ('Primeiro-Tenente',            '1T', 90),
    ('Segundo-Tenente',             '2T', 100),
    ('Aspirante-a-Oficial',         'AP', 110),
    ('Suboficial',                  'SO', 120),
    ('Primeiro-Sargento',           '1S', 130),
    ('Segundo-Sargento',            '2S', 140),
    ('Terceiro-Sargento',           '3S', 150),
    ('Taifeiro-Mor',                'TM', 160),
    ('Cabo',                        'CB', 170),
    ('Soldado',                     'SD', 180),
    ('Soldado de Primeira Classe',  'S1', 175),
    ('Soldado de Segunda Classe',   'S2', 176),
    ('Taifeiro de Primeira Classe', 'T1', 177),
    ('Taifeiro de Segunda Classe',  'T2', 178);

-- Organizações militares (OM)
CREATE TABLE t_organizacao_militar (
    id_organizacao_militar BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_organizacao_militar VARCHAR(255) NOT NULL,
    sg_organizacao_militar VARCHAR(20) NOT NULL UNIQUE,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_alteracao TIMESTAMP,
    nr_versao INTEGER NOT NULL DEFAULT 0
);

-- Catálogo de OMs da FAB (nome e sigla) -- fonte: Catálogo Telefônico oficial
-- (fab.mil.br), 322 OMs listadas. Sete linhas tiveram nome ou sigla ausente
-- ou ambíguo no próprio catálogo-fonte e foram tratadas assim:
--   - "ESD": nome do órgão vinha vazio no catálogo-fonte -- excluída (nenhum
--     dado utilizável).
--   - "VII COMAR": nome vinha vazio no catálogo-fonte -- preenchido seguindo
--     o mesmo padrão das outras seis (I-VI COMAR), fato público já
--     consolidado, não uma suposição sobre nome ambíguo.
--   - Adidância na Indonésia/Tailândia/Vietnã e Adidância na Suécia: sem
--     sigla própria no catálogo-fonte -- ADID-INDO/ADID-SUE são siglas
--     sintéticas (não oficiais), só para satisfazer a UNIQUE NOT NULL.
--   - "EBL" (Escritório Brasileiro de Ligação) aparece duas vezes no
--     catálogo-fonte com a mesma sigla para unidades fisicamente distintas
--     (Israel e CABW/EUA) -- desambiguado como EBL-ISRAEL/EBL-CABW.
INSERT INTO t_organizacao_militar (nm_organizacao_militar, sg_organizacao_militar) VALUES
    ('Academia da Força Aérea', 'AFA'),
    ('Adidância Aeronáutica dos Estados Unidos da América', 'EEUU'),
    ('Adidância Indonésia Adido de Defesa Naval e Aeronáutico do Brasil na Indonésia, na Tailândia e no Vietnã', 'ADID-INDO'),
    ('Adidância Suécia Adido de Defesa, Naval, do Exército e Aeronáutica na Suécia', 'ADID-SUE'),
    ('Assessoria de Segurança Operacional do Controle do Espaço Aéreo', 'ASOCEA'),
    ('Assessoria Parlamentar e de Relações Institucionais do Comando da Aeronáutica', 'ASPAER'),
    ('Base Aérea de Anápolis', 'BAAN'),
    ('Base Aérea de Belém', 'BABE'),
    ('Base Aérea de Boa Vista', 'BABV'),
    ('Base Aérea de Brasília', 'BABR'),
    ('Base Aérea de Campo Grande', 'BACG'),
    ('Base Aérea de Canoas', 'BACO'),
    ('Base Aérea de Florianópolis', 'BAFL'),
    ('Base Aérea de Fortaleza', 'BAFZ'),
    ('Base Aérea de Manaus', 'BAMN'),
    ('Base Aérea de Natal', 'BANT'),
    ('Base Aérea de Porto Velho', 'BAPV'),
    ('Base Aérea de Recife', 'BARF'),
    ('Base Aérea de Salvador', 'BASV'),
    ('Base Aérea de Santa Cruz', 'BASC'),
    ('Base Aérea de Santa Maria', 'BASM'),
    ('Base Aérea de Santos', 'BAST'),
    ('Base Aérea de São Paulo', 'BASP'),
    ('Base Aérea do Galeão', 'BAGL'),
    ('Base Aérea dos Afonsos', 'BAAF'),
    ('Base de Recepção de Veteranos', 'BREVET'),
    ('Grupamento de Segurança e Defesa dos Afonsos', 'GSD-AF'),
    ('Caixa de Financiamento Imobiliário da Aeronáutica', 'CFIAE'),
    ('Campo de Provas Brigadeiro Velloso', 'CPBV'),
    ('Centro de Apoio Administrativo da Aeronáutica', 'CEAP'),
    ('Centro de Aquisições Específicas', 'CAE'),
    ('Centro de Catalogação da Aeronáutica', 'CECAT'),
    ('Centro de Computação da Aeronáutica de Brasília', 'CCA-BR'),
    ('Centro de Computação da Aeronáutica de São José dos Campos', 'CCA-SJ'),
    ('Centro de Computação de Aeronáutica do Rio de Janeiro', 'CCA-RJ'),
    ('Centro de Comunicação Social da Aeronáutica', 'CECOMSAER'),
    ('Centro de Controle Interno da Aeronáutica', 'CENCIAR'),
    ('Centro de Defesa Cibernética da Aeronáutica', 'CDCAER'),
    ('Centro de Documentação Aeronáutica', 'CENDOC'),
    ('Centro de Estudos e Projetos de Engenharia', 'CEPE'),
    ('Centro de Gerenciamento da Navegação Aérea', 'CGNA'),
    ('Centro de Instrução e Adaptação da Aeronáutica', 'CIAAR'),
    ('Centro de Inteligência da Aeronáutica', 'CIAER'),
    ('Centro de Investigação e Prevenção de Acidentes Aeronáuticos (Cenipa)', 'CENIPA'),
    ('Centro de Lançamento da Barreira do Inferno', 'CLBI'),
    ('Centro de Lançamento de Alcântara', 'CLA'),
    ('Centro de Medicina Aeroespacial', 'CEMAL'),
    ('Centro de Preparação de Oficiais da Reserva da Aeronáutica de São José dos Campos', 'CPORAER-SJ'),
    ('Centro de Transporte Logístico da Aeronáutica', 'CTLA'),
    ('Centro Gerontológica de Aeronáutica Eduardo Gomes', 'CGABEG'),
    ('Centro Integrado de Meteorologia Aeronáutica', 'CIMAER'),
    ('Centro Logístico da Aeronáutica', 'CELOG'),
    ('Primeiro Centro Integrado de Defesa Aérea e Controle de Tráfego Aéreo', 'CINDACTA I'),
    ('Quarto Centro Integrado de Defesa Aérea e Controle de Tráfego Aéreo', 'CINDACTA IV'),
    ('Segundo Centro Integrado de Defesa Aérea e Controle de Tráfego Aéreo', 'CINDACTA II'),
    ('Terceiro Centro Integrado de Defesa Aérea e Controle de Tráfego Aéreo', 'CINDACTA III'),
    ('Colégio Brigadeiro Newton Braga', 'CBNB'),
    ('Comando da Aeronáutica', 'COMAER'),
    ('Comando de Defesa Cibernética', 'COMDCIBER'),
    ('Comando de Operações Aeroespaciais', 'COMAE'),
    ('Comando de Preparo', 'COMPREP'),
    ('Comando-Geral de Apoio', 'COMGAP'),
    ('Comando-Geral do Pessoal', 'COMGEP'),
    ('Primeiro Comando Aéreo Regional', 'I COMAR'),
    ('Segundo Comando Aéreo Regional', 'II COMAR'),
    ('Terceiro Comando Aéreo Regional', 'III COMAR'),
    ('Quarto Comando Aéreo Regional', 'IV COMAR'),
    ('Sétimo Comando Aéreo Regional', 'VII COMAR'),
    ('Sexto Comando Aéreo Regional', 'VI COMAR'),
    ('Quinto Comando Aéreo Regional', 'V COMAR'),
    ('Comissão Aeronáutica Brasileira em Washington', 'CABW'),
    ('Comissão Aeronáutica Brasileira na Europa', 'CABE'),
    ('Comissão Coordenadora do Programa Aeronave de Combate', 'COPAC'),
    ('Comissão de Aeroportos da Região Amazônica', 'COMARA'),
    ('Comissão de Desportos da Aeronáutica', 'CDA'),
    ('Comissão de Implantação do Sistema de Controle do Espaço Aéreo', 'CISCEA'),
    ('Consultoria Jurídica Adjunta do Comando da Aeronáutica', 'COJAER'),
    ('Departamento de Ciência e Tecnologia Aeroespacial', 'DCTA'),
    ('Departamento de Controle do Espaço Aéreo', 'DECEA'),
    ('Destacamento de Aeronáutica de Caravelas', 'DESTAE-CV'),
    ('Destacamento de Aeronáutica de Fernando de Noronha', 'DESTAE-FN'),
    ('Destacamento de Aeronáutica de Macapá', 'DESTAE-MQ'),
    ('Destacamento de Aeronáutica de Mossoró', 'DESTAE-MS'),
    ('Destacamento de Aeronáutica de São Gabriel da Cachoeira', 'DASG'),
    ('Destacamento de Controle do Espaço Aéreo: Barbacena', 'DTCEA-BQ'),
    ('Destacamento de Controle do Espaço Aéreo de Bacacheri', 'DTCEA-BI'),
    ('Destacamento de Controle do Espaço Aéreo de Guaratinguetá', 'DTCEA-GW'),
    ('Destacamento de Controle do Espaço Aéreo de Marte', 'DTCEA-MT'),
    ('Destacamento de Controle do Espaço Aéreo de Santa Cruz', 'DTCEA-SC'),
    ('Destacamento de Controle do Espaço Aéreo de Santa Maria', 'DTCEA-SM'),
    ('Destacamento de Controle do Espaço Aéreo de Santos', 'DTCEA-ST'),
    ('Destacamento de Controle do Espaço Aéreo de São Félix do Araguaia', 'DTCEA-FA'),
    ('Destacamento de Controle do Espaço Aéreo de São Paulo', 'DTCEA-SP'),
    ('Destacamento de Controle do Espaço Aéreo de Sinop', 'DTCEA-SI'),
    ('Destacamento de Controle do Espaço Aéreo do Galeão', 'DTCEA-GL'),
    ('Destacamento de Controle do Espaço Aéreo dos Afonsos', 'DTCEA-AF'),
    ('Destacamento de Controle do Espaço Aéreo e Telemática do Rio de Janeiro', 'DTCEATM-RJ'),
    ('Destacamento de Controle do Espaço Aéreo: Anápolis', 'DTCEA-AN'),
    ('Destacamento de Controle do Espaço Aéreo: Aracaju', 'DTCEA-AR'),
    ('Destacamento de Controle do Espaço Aéreo: Barra do Garças', 'DTCEA-BW'),
    ('Destacamento de Controle do Espaço Aéreo: Belém', 'DTCEA-BE'),
    ('Destacamento de Controle do Espaço Aéreo: Boa Vista', 'DTCEA-BV'),
    ('Destacamento de Controle do Espaço Aéreo: Bom Jesus da Lapa', 'DTCEA-LP'),
    ('Destacamento de Controle do Espaço Aéreo: Brasília', 'DTCEA-BR'),
    ('Destacamento de Controle do Espaço Aéreo: Cachimbo', 'DTCEA-CC'),
    ('Destacamento de Controle do Espaço Aéreo: Campo Grande', 'DTCEA-CG'),
    ('Destacamento de Controle do Espaço Aéreo: Canguçu', 'DTCEA-CGU'),
    ('Destacamento de Controle do Espaço Aéreo: Canoas', 'DTCEA-CO'),
    ('Destacamento de Controle do Espaço Aéreo: Catanduvas', 'DTCEA-CDT'),
    ('Destacamento de Controle do Espaço Aéreo: Chapada dos Guimarães', 'DTCEA-GI'),
    ('Destacamento de Controle do Espaço Aéreo: Conceição do Araguia', 'DTCEA-AA'),
    ('Destacamento de Controle do Espaço Aéreo: Confins', 'DTCEA-CF'),
    ('Destacamento de Controle do Espaço Aéreo: Corumbá', 'DTCEA-CR'),
    ('Destacamento de Controle do Espaço Aéreo: Cruzeiro do Sul', 'DTCEA-CZ'),
    ('Destacamento de Controle do Espaço Aéreo: Cuiabá', 'DTCEA-CY'),
    ('Destacamento de Controle do Espaço Aéreo: Curitiba', 'DTCEA-CT'),
    ('Destacamento de Controle do Espaço Aéreo: Eduardo Gomes', 'DTCEA-EG'),
    ('Destacamento de Controle do Espaço Aéreo: Eirunepé', 'DTCEA-EI'),
    ('Destacamento de Controle do Espaço Aéreo: Fernando de Noronha', 'DTCEA-FN'),
    ('Destacamento de Controle do Espaço Aéreo: Florianópolis', 'DTCEA-FL'),
    ('Destacamento de Controle do Espaço Aéreo: Fortaleza', 'DTCEA-FZ'),
    ('Destacamento de Controle do Espaço Aéreo: Foz do Iguaçu', 'DTCEA-FI'),
    ('Destacamento de Controle do Espaço Aéreo: Gama', 'DTCEA-GA'),
    ('Destacamento de Controle do Espaço Aéreo: Guajará-Mirim', 'DTCEA-GM'),
    ('Destacamento de Controle do Espaço Aéreo: Imperatriz', 'DTCEA-IZ'),
    ('Destacamento de Controle do Espaço Aéreo: Jacareacanga', 'DTCEA-EK'),
    ('Destacamento de Controle do Espaço Aéreo: Lagoa Santa', 'DTCEA-LS'),
    ('Destacamento de Controle do Espaço Aéreo: Macapá', 'DTCEA-MQ'),
    ('Destacamento de Controle do Espaço Aéreo: Maceió', 'DTCEA-MO'),
    ('Destacamento de Controle do Espaço Aéreo: Manaus', 'DTCEA-MN'),
    ('Destacamento de Controle do Espaço Aéreo: Manicoré', 'DTCEA-MY'),
    ('Destacamento de Controle do Espaço Aéreo: Morro da Igreja', 'DTCEA-MDI'),
    ('Destacamento de Controle do Espaço Aéreo: Natal', 'DTCEA-NT'),
    ('Destacamento de Controle do Espaço Aéreo: Oiapoque', 'DTCEA-OI'),
    ('Destacamento de Controle do Espaço Aéreo: Petrolina', 'DTCEA-PL'),
    ('Destacamento de Controle do Espaço Aéreo: Pico do Couto', 'DTCEA-PCO'),
    ('Destacamento de Controle do Espaço Aéreo: Pirassununga', 'DTCEA-YS'),
    ('Destacamento de Controle do Espaço Aéreo: Porto Esperidião', 'DTCEA-EP'),
    ('Destacamento de Controle do Espaço Aéreo: Porto Velho', 'DTCEA-PV'),
    ('Destacamento de Controle do Espaço Aéreo: Recife', 'DTCEA-RF'),
    ('Destacamento de Controle do Espaço Aéreo: Rio Branco', 'DTCEA-RB'),
    ('Destacamento de Controle do Espaço Aéreo: Salvador', 'DTCEA-SV'),
    ('Destacamento de Controle do Espaço Aéreo: Santa Teresa', 'DTCEA-STA'),
    ('Destacamento de Controle do Espaço Aéreo: Santarém', 'DTCEA-SN'),
    ('Destacamento de Controle do Espaço Aéreo: Santiago', 'DTCEA-STI'),
    ('Destacamento de Controle do Espaço Aéreo: São Félix do Xingu', 'DTCEA-FX'),
    ('Destacamento de Controle do Espaço Aéreo: São Gabriel da Cachoeira', 'DTCEA-UA'),
    ('Destacamento de Controle do Espaço Aéreo: São José dos Campos', 'DTCEA-SJ'),
    ('Destacamento de Controle do Espaço Aéreo: São Luís', 'DTCEA-SL'),
    ('Destacamento de Controle do Espaço Aéreo: São Roque', 'DTCEA-SRO'),
    ('Destacamento de Controle do Espaço Aéreo: Tabatinga', 'DTCEA-TT'),
    ('Destacamento de Controle do Espaço Aéreo: Tanabi', 'DTCEA-TNB'),
    ('Destacamento de Controle do Espaço Aéreo: Tefé', 'DTCEA-TF'),
    ('Destacamento de Controle do Espaço Aéreo: Três Marias', 'DTCEA-TRM'),
    ('Destacamento de Controle do Espaço Aéreo: Uruguaiana', 'DTCEA-UG'),
    ('Destacamento de Controle do Espaço Aéreo: Vilhena', 'DTCEA-VH'),
    ('Destacamento de Suprimento e Manutenção de Manaus', 'DSM-MN'),
    ('Destacamento de Telecomunicações por Satélite de Brasília', 'DTS-BR'),
    ('Diretoria de Administração da Aeronáutica', 'DIRAD'),
    ('Diretoria de Administração do Pessoal', 'DIRAP'),
    ('Diretoria de Economia e Finanças da Aeronáutica', 'DIREF'),
    ('Diretoria de Ensino', 'DIRENS'),
    ('Diretoria de Infraestrutura da Aeronáutica', 'DIRINFRA'),
    ('Diretoria de Material Aeronáutico e Bélico', 'DIRMAB'),
    ('Diretoria de Saúde da Aeronáutica', 'DIRSA'),
    ('Diretoria de Tecnologia da Informação da Aeronáutica', 'DTI'),
    ('Destacamento de Controle do Espaço Aéreo de Catanduvas', 'DTCEA-CTD'),
    ('Escola de Aperfeiçoamento de Oficiais da Aeronáutica', 'EAOAR'),
    ('Escola de Comando e Estado Maior da Aeronaútica', 'ECEMAR'),
    ('Escola de Especialistas de Aeronáutica', 'EEAR'),
    ('Escola Preparatória de Cadetes do Ar', 'EPCAR'),
    ('Escola Superior de Guerra', 'ESG'),
    ('Esquadrão Aeroterrestre de Salvamento (Para-Sar)', 'EAS'),
    ('Esquadrão de Demonstração Aérea', 'EDA'),
    ('Primeiro Esquadrão de Transporte Aéreo', '1º ETA'),
    ('Primeiro Esquadrão do Décimo Grupo de Aviação', '1º/10º GAV'),
    ('Primeiro Esquadrão do Décimo Primeiro Grupo de Aviação', '1º/11º GAV'),
    ('Primeiro Esquadrão do Décimo Quarto Grupo de Aviação', '1º/14º GAV'),
    ('Primeiro Esquadrão do Décimo Quinto Grupo de Aviação', '1º/15º GAV'),
    ('Primeiro Esquadrão do Décimo Segundo Grupo de Aviação', '1º/12º GAV'),
    ('Primeiro Esquadrão do Décimo Sexto Grupo de Aviação', '1º/16º GAV'),
    ('Primeiro Esquadrão do Nono Grupo de Aviação', '1º/9º GAV'),
    ('Primeiro Esquadrão do Oitavo Grupo de Aviação', '1º/8º GAV'),
    ('Primeiro Esquadrão do Primeiro Grupo de Comunicações e Controle', '1º/1º GCC'),
    ('Primeiro Esquadrão do Primeiro Grupo de Transporte', '1º/1º GT'),
    ('Primeiro Esquadrão do Quinto Grupo de Aviação', '1º/5º GAV'),
    ('Primeiro Esquadrão do Segundo Grupo de Transporte', '1º/2º GT'),
    ('Primeiro Esquadrão do Sétimo Grupo de Aviação', '1º/7º GAV'),
    ('Primeiro Esquadrão do Terceiro Grupo de Aviação', '1º/3º GAV'),
    ('Quarto Esquadrão do Primeiro Grupo de Comunicações e Controle', '4º/1º GCC'),
    ('Quinto Esquadrão de Transporte Aéreo', '5º ETA'),
    ('Quinto Esquadrão do Oitavo Grupo de Aviação', '5º/8º GAV'),
    ('Quinto Esquadrão do Primeiro Grupo de Comunicações e Controle', '5º/1º GCC'),
    ('Segundo Esquadrão de Transporte Aéreo', '2º ETA'),
    ('Segundo Esquadrão do Décimo Grupo de Aviação', '2º/10º GAV'),
    ('Segundo Esquadrão do Oitavo Grupo de Aviação', '2º/8º GAV'),
    ('Segundo Esquadrão do Primeiro Grupo de Comunicações e Controle', '2º/1º GCC'),
    ('Segundo Esquadrão do Quinto Grupo de Aviação', '2º/5º GAV'),
    ('Segundo Esquadrão do Segundo Grupo de Transporte', '2º/2º GT'),
    ('Segundo Esquadrão do Sétimo Grupo de Aviação', '2º/7º GAV'),
    ('Segundo Esquadrão do Sexto Grupo de Aviação', '2º/6º GAV'),
    ('Segundo Esquadrão do Terceiro Grupo de Aviação', '2º/3º GAV'),
    ('Sétimo Esquadrão de Transporte Aéreo', '7º ETA'),
    ('Sétimo Esquadrão do Oitavo Grupo de Aviação', '7º/8º GAV'),
    ('Sexto Esquadrão de Transporte Aéreo', '6º ETA'),
    ('Terceiro Esquadrão de Transporte Aéreo', '3º ETA'),
    ('Terceiro Esquadrão do Décimo Grupo de Aviação', '3º/10º GAV'),
    ('Terceiro Esquadrão do Oitavo Grupo de Aviação', '3º/8º GAV'),
    ('Terceiro Esquadrão do Primeiro Grupo de Comunicações e Controle', '3º/1º GCC'),
    ('Terceiro Esquadrão do Sétimo Grupo de Aviação', '3º/7º GAV'),
    ('Terceiro Esquadrão do Terceiro Grupo de Aviação', '3º/3º GAV'),
    ('Estado-Maior da Aeronáutica', 'EMAER'),
    ('Fazenda da Aeronáutica de Pirassununga', 'FAYS'),
    ('Gabinete do Comandante da Aeronáutica', 'GABAER'),
    ('Grupamento de Apoio de Belém', 'GAP-BE'),
    ('Grupamento de Apoio de Brasília', 'GAP-BR'),
    ('Grupamento de Apoio de Canoas', 'GAP-CO'),
    ('Grupamento de Apoio de Lagoa Santa', 'GAP-LS'),
    ('Grupamento de Apoio de Manaus', 'GAP-MN'),
    ('Grupamento de Apoio de Recife', 'GAP-RF'),
    ('Grupamento de Apoio de São José dos Campos', 'GAP-SJ'),
    ('Grupamento de Apoio de São Paulo', 'GAP-SP'),
    ('Grupamento de Apoio do Distrito Federal', 'GAP-DF'),
    ('Grupamento de Apoio do Galeão', 'GAP-GL'),
    ('Grupamento de Apoio do Rio de Janeiro', 'GAP-RJ'),
    ('Grupamento de Apoio dos Afonsos', 'GAP-AF'),
    ('Grupamento de Apoio Logístico', 'GAL'),
    ('Grupamento de Apoio Logístico de Campanha', 'GALC'),
    ('Grupo de Instrução Tática e Especializada', 'GITE'),
    ('Grupo de Transporte Especial', 'GTE'),
    ('Grupo Especial de Inspeção em Vôo', 'GEIV'),
    ('Primeiro Grupo de Aviação de Caça', '1º GAVCA'),
    ('Primeiro Grupo de Comunicações e Controle', '1º GCC'),
    ('Primeiro Grupo de Defesa Aérea', '1º GDA'),
    ('Primeiro Grupo de Defesa Antiaérea', '1º GDAAE'),
    ('Primeiro Grupo de Transporte de Tropa', '1º GTT'),
    ('Segundo Grupo de Defesa Antiaérea', '2º GDAAE'),
    ('Terceiro Grupo de Defesa Antiaérea', '3º GDAAE'),
    ('Hospital Central da Aeronáutica', 'HCA'),
    ('Hospital das Forças Armadas', 'HFA'),
    ('Hospital de Aeronáutica de Belém', 'HABE'),
    ('Hospital de Aeronáutica de Canoas', 'HACO'),
    ('Hospital de Aeronáutica de Manaus', 'HAMN'),
    ('Hospital de Aeronáutica de Recife', 'HARF'),
    ('Hospital de Aeronáutica dos Afonsos', 'HAAF'),
    ('Hospital de Força Aérea de Brasília', 'HFAB'),
    ('Hospital de Força Aérea de São Paulo', 'HFASP'),
    ('Hospital de Força Aérea do Galeão', 'HFAG'),
    ('Instituto de Aeronáutica e Espaço', 'IAE'),
    ('Instituto de Aplicações Operacionais', 'IAOP'),
    ('Instituto de Cartografia Aeronáutica', 'ICA'),
    ('Instituto de Controle do Espaço Aéreo', 'ICEA'),
    ('Instituto de Estudos Avançados', 'IEAV'),
    ('Instituto de Fomento e Coordenação Industrial', 'IFI'),
    ('Instituto de Logística da Aeronáutica', 'ILA'),
    ('Instituto de Pesquisas e Ensaios em Voo', 'IPEV'),
    ('Instituto de Psicologia da Aeronáutica', 'IPA'),
    ('Instituto Histórico-Cultural da Aeronáutica', 'INCAER'),
    ('Instituto Medicina Aeroespacial Brigadeiro Médico Roberto Teixeira', 'IMAE'),
    ('Instituto Tecnológico de Aeronáutica', 'ITA'),
    ('Laboratório Químico-Farmacêutico da Aeronáutica', 'LAQFA'),
    ('Ministério da Defesa', 'MD'),
    ('Missão Técnica Aeronáutica Brasileira em Assunção', 'MTAB'),
    ('Museu Aeroespacial', 'MUSAL'),
    ('Odontoclínica de Aeronáutica de Brasília', 'OABR'),
    ('Odontoclínica de Aeronáutica de Recife', 'OARF'),
    ('Odontoclínica de Aeronáutica Santos-Dumont', 'OASD'),
    ('Organização de Aviação Civil Internacional', 'OACI'),
    ('Parque de Material Aeronáutico de Lagoa Santa', 'PAMA-LS'),
    ('Parque de Material Aeronáutico de São Paulo', 'PAMA-SP'),
    ('Parque de Material Aeronáutico do Galeão', 'PAMA-GL'),
    ('Parque de Material Bélico de Aeronáutica do Rio de Janeiro', 'PAMB-RJ'),
    ('Parque de Material de Eletrônica da Aeronáutica do Rio de Janeiro', 'PAME-RJ'),
    ('Prefeitura de Aeronáutica de Anápolis', 'PAAN'),
    ('Prefeitura de Aeronáutica de Belém', 'PABE'),
    ('Prefeitura de Aeronáutica de Boa Vista', 'PABV'),
    ('Prefeitura de Aeronáutica de Brasília', 'PABR'),
    ('Prefeitura de Aeronáutica de Canoas', 'PACO'),
    ('Prefeitura de Aeronáutica de Guaratinguetá', 'PAGW'),
    ('Prefeitura de Aeronáutica de Lagoa Santa', 'PALS'),
    ('Prefeitura de Aeronáutica de Manaus', 'PAMN'),
    ('Prefeitura de Aeronáutica de Natal', 'PANT'),
    ('Prefeitura de Aeronáutica de Pirassununga', 'PAYS'),
    ('Prefeitura de Aeronáutica de Porto Velho', 'PAPV'),
    ('Prefeitura de Aeronáutica de Recife', 'PARF'),
    ('Prefeitura de Aeronáutica de Santa Cruz', 'PASC'),
    ('Prefeitura de Aeronáutica de Santa Maria', 'PASM'),
    ('Prefeitura de Aeronáutica de Santos', 'PAST'),
    ('Prefeitura de Aeronáutica de São José dos Campos', 'PASJ'),
    ('Prefeitura de Aeronáutica de São Paulo', 'PASP'),
    ('Prefeitura de Aeronáutica do Galeão', 'PAGL'),
    ('Prefeitura de Aeronáutica dos Afonsos', 'PAAF'),
    ('Presidência da República', 'PR'),
    ('Secretaria de Avaliação e Promoções', 'SECPROM'),
    ('Secretaria de Economia, Finanças e Administração da Aeronáutica', 'SEFA'),
    ('Primeiro Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA I'),
    ('Quarto Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA IV'),
    ('Quinto Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA V'),
    ('Segundo Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA II'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica de Belém', 'SEREP-BE'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica de Canoas', 'SEREP-CO'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica de Manaus', 'SEREP-MN'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica de Recife', 'SEREP-RF'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica de São Paulo', 'SEREP-SP'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica do Rio de Janeiro', 'SEREP-RJ'),
    ('Serviço Geral de Correspondência e Arquivo da Aeronáutica', 'SEGECAE'),
    ('Sétimo Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA VII'),
    ('Sexto Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA VI'),
    ('Terceiro Serviço Regional de Investigação e Prevenção de Acidentes Aeronáuticos', 'SERIPA III'),
    ('Sociedade Brasileira de Direito Aeroespacial', 'SBDA'),
    ('Superior Tribunal Militar', 'STM'),
    ('Escritório Brasileiro de Ligação (Brazilian Liaison Office) em Israel', 'EBL-ISRAEL'),
    ('Escritório Brasileiro de Ligação da CABW', 'EBL-CABW'),
    ('Junta de Julgamento da Aeronáutica', 'JJAER'),
    ('Junta Interamericana de Defesa', 'JID'),
    ('Memorial Aeroespacial Brasileiro', 'MAB'),
    ('Representação Brasileira na Junta Interamericana de Defesa', 'RBJID'),
    ('Universidade da Força Aérea', 'UNIFA'),
    ('Vice-Presidência da República', 'VPR'),
    ('Centro Regional de Controle do Espaço Aéreo Sudeste', 'CRCEA-SE'),
    ('Serviço de Recrutamento e Preparo de Pessoal da Aeronáutica de Brasília', 'SEREP-BR');

-- OM "sistema" -- dona de qualquer documento sem autoria real (ver
-- t_usuario abaixo) e reaproveitada pelo DataSeeder como OM provisória do
-- admin padrão até a tela de administração de usuários existir.
INSERT INTO t_organizacao_militar (nm_organizacao_militar, sg_organizacao_militar)
VALUES ('Organização Padrão do Sistema', 'SISTEMA');

-- Usuários. nr_cpf é a chave de login (e o identificador usado para
-- compartilhar documentos com outra pessoa) -- ver DocumentoCompartilhamento.
-- Cada usuário pertence a exatamente uma OM (fl_ativo permite desativar
-- sem apagar o vínculo de autoria dos documentos já criados por ele).
CREATE TABLE t_usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario VARCHAR(255) NOT NULL,
    nr_cpf VARCHAR(11) NOT NULL UNIQUE,
    tx_senha_hash VARCHAR(255) NOT NULL,
    om_id BIGINT NOT NULL REFERENCES t_organizacao_militar(id_organizacao_militar),
    posto_graduacao_id BIGINT REFERENCES t_posto_graduacao(id_posto_graduacao),
    tx_nome_guerra VARCHAR(60),
    tx_email VARCHAR(150),
    fl_ativo BOOLEAN NOT NULL DEFAULT true,
    -- Usuário técnico dono de qualquer documento sem autor real -- nunca
    -- autentica (fl_ativo=false, hash inutilizável) e nunca aparece como
    -- opção de compartilhamento.
    fl_sistema BOOLEAN NOT NULL DEFAULT false,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_alteracao TIMESTAMP,
    nr_versao INTEGER NOT NULL DEFAULT 0
);

-- Usuário "sistema" -- distinto do usuário administrativo padrão (ver
-- DataSeeder.java), que é uma conta de login real; este aqui nunca loga.
INSERT INTO t_usuario (nm_usuario, nr_cpf, tx_senha_hash, om_id, fl_ativo, fl_sistema)
VALUES (
    'Usuário Sistema',
    '00000000000',
    '!',
    (SELECT id_organizacao_militar FROM t_organizacao_militar WHERE sg_organizacao_militar = 'SISTEMA'),
    false,
    true
);

-- Papéis do usuário (EDIT / APROV / PUBLIC / AUDITOR / ADMIN) -- ver
-- PapelEnum.java. sg_papel é VARCHAR livre (sem CHECK constraint), então um
-- novo valor de enum nunca exige alteração de schema.
CREATE TABLE t_usuario_papel (
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    sg_papel VARCHAR(20) NOT NULL,
    PRIMARY KEY (usuario_id, sg_papel)
);

-- ── Documento e histórico ─────────────────────────────────────────────────────

CREATE TABLE t_documento (
    id_documento           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    especie_normativa_id   BIGINT NOT NULL REFERENCES t_especie_normativa (id_especie_normativa),
    assunto_basico_id      BIGINT NOT NULL REFERENCES t_assunto_basico (id_assunto_basico),
    nr_numero_secundario   INTEGER NOT NULL,
    nm_titulo_documento    VARCHAR(255) NOT NULL,
    st_documento           VARCHAR(30) NOT NULL,
    autor_id               BIGINT NOT NULL REFERENCES t_usuario (id_usuario),
    om_id                  BIGINT NOT NULL REFERENCES t_organizacao_militar (id_organizacao_militar),
    -- Pessoa específica (papel APROV) escolhida por quem enviou para revisão -- só ela
    -- pode agir no documento enquanto ele estiver em EM_REVISAO/ANALISE_REVOGACAO (ver
    -- DocumentoAcessoService.podeMudarStatus). Reaproveitado nas duas etapas de revisão
    -- (fluxo normal e revogação), sempre sobrescrito a cada novo envio.
    revisor_atribuido_id    BIGINT REFERENCES t_usuario (id_usuario),
    -- Pessoa específica (papel PUBLIC) escolhida pelo APROV ao aprovar -- só ela pode
    -- agir no documento enquanto ele estiver em EM_PUBLICACAO/EM_REVOGACAO. Mesmo
    -- padrão de revisor_atribuido_id, reaproveitado nas duas etapas de publicação.
    publicador_atribuido_id BIGINT REFERENCES t_usuario (id_usuario),
    dt_criacao             TIMESTAMP,
    dt_alteracao           TIMESTAMP,
    dt_minuta               TIMESTAMP,
    dt_em_revisao          TIMESTAMP,
    dt_aprovacao           TIMESTAMP,
    dt_em_publicacao       TIMESTAMP,
    dt_publicacao          TIMESTAMP,
    dt_analise_revogacao    TIMESTAMP,
    dt_em_revogacao        TIMESTAMP,
    dt_revogacao            TIMESTAMP,
    dt_cancelamento         TIMESTAMP,
    dt_em_alteracao         TIMESTAMP,
    -- Timestamp próprio para EM_ALTERACAO -> ALTERADO, separado de dt_aprovacao para
    -- não sobrescrever o momento da aprovação original do fluxo normal.
    dt_alterado             TIMESTAMP,
    url_pdf                 VARCHAR(255),
    -- Mesmas transições de status geram/armazenam os dois (ver DocumentoStatusService) --
    -- HTML e PDF são sempre regenerados juntos, nunca um sem o outro.
    url_html                 VARCHAR(255),
    nr_replicas              INTEGER NOT NULL DEFAULT 0,
    tx_portaria_referencia   VARCHAR(255),
    tx_bca_referencia        VARCHAR(255),
    dt_portaria_referencia   TIMESTAMP,
    dt_bca_referencia        TIMESTAMP,
    nr_versao                INTEGER NOT NULL
);

-- Coautores de um documento (compartilhamento). Dá direito de EDITAR e,
-- enquanto o documento estiver em RASCUNHO/MINUTA, de EXCLUIR -- ver
-- DocumentoAcessoService. Só o autor do documento pode compartilhar ou
-- remover um coautor.
CREATE TABLE t_documento_compartilhamento (
    id_compartilhamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento(id_documento) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    dt_compartilhamento TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (documento_id, usuario_id)
);

CREATE TABLE t_historico_documento (
    id_historico        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id        BIGINT NOT NULL REFERENCES t_documento (id_documento),
    tx_descricao        VARCHAR(255) NOT NULL,
    sg_tipo_alteracao   VARCHAR(30) NOT NULL,
    sg_status_anterior  VARCHAR(30),
    sg_status_novo      VARCHAR(30),
    nm_usuario          VARCHAR(255),
    dt_registro         TIMESTAMP
);

CREATE TABLE t_emenda_historico (
    id_emenda            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id         BIGINT NOT NULL,
    secao                VARCHAR(30) NOT NULL,
    elemento_id          BIGINT NOT NULL,
    acao                 VARCHAR(20) NOT NULL,
    tx_conteudo_anterior TEXT,
    tx_conteudo_novo     TEXT,
    tx_titulo_anterior   VARCHAR(255),
    tx_titulo_novo       VARCHAR(255),
    tx_justificativa     TEXT,
    dt_emenda            TIMESTAMP,
    -- Marca a qual ciclo de publicação (portaria/BCA) esta linha pertence -- carimbada
    -- em EmendaService.consolidarPublicacao(), o mesmo momento em que a cláusula de
    -- emenda é congelada nos elementos. NULL significa que a linha pertence ao ciclo
    -- de alteração ainda em andamento (ainda não publicado).
    tx_ciclo_referencia  TEXT
);

-- Log de acesso/ações a nível de documento (quem viu, quem editou, quando --
-- ver LogAuditoriaService). documento_id/documento_descricao são um
-- snapshot no momento da ação, sem FK para t_documento: o documento pode
-- ser excluído mais tarde (ver DocumentoAcessoService.podeExcluir) e a
-- trilha de auditoria precisa sobreviver a isso.
CREATE TABLE t_log_auditoria (
    id_log_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario),
    documento_id BIGINT NOT NULL,
    documento_descricao VARCHAR(255) NOT NULL,
    sg_acao VARCHAR(30) NOT NULL,
    tx_detalhe VARCHAR(500),
    dt_ocorrencia TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_log_auditoria_documento ON t_log_auditoria(documento_id);
CREATE INDEX idx_log_auditoria_usuario ON t_log_auditoria(usuario_id);
CREATE INDEX idx_log_auditoria_dt_ocorrencia ON t_log_auditoria(dt_ocorrencia);

-- Notificação real (ver NotificacaoService): gravada na mesma transação da
-- ação que a gera (compartilhamento, documento entrando em situação que
-- pede aprovação) e entregue ao vivo por SSE quando o destinatário está
-- conectado (NotificacaoEmitterRegistry) -- esta tabela é sempre a fonte
-- de verdade, então também cobre quem estava offline no momento do evento.
CREATE TABLE t_notificacao (
    id_notificacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    sg_tipo VARCHAR(30) NOT NULL,
    tx_mensagem VARCHAR(500) NOT NULL,
    documento_id BIGINT NOT NULL,
    documento_descricao VARCHAR(255) NOT NULL,
    fl_lida BOOLEAN NOT NULL DEFAULT false,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_leitura TIMESTAMP
);

CREATE INDEX idx_notificacao_destinatario ON t_notificacao(destinatario_id, fl_lida);

-- Cada portaria do ciclo de vida de um documento (edição, sucessivas alterações,
-- revogação) é um registro próprio, com o PDF preservado intacto no MinIO -- nunca
-- mesclado com o PDF gerado do documento (mesclar invalidaria uma futura assinatura
-- digital, que cobre um intervalo de bytes exato do arquivo original).
--
-- Nome deliberadamente diferente de t_portaria, que já é a tabela de
-- ItemPartePreliminar (ver abaixo).
CREATE TABLE t_portaria_publicacao (
    id_portaria_publicacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento(id_documento),
    sg_tipo VARCHAR(20) NOT NULL,       -- EDICAO | ALTERACAO | REVOGACAO
    nr_sequencial INTEGER,               -- só para ALTERACAO (1, 2, 3...)
    tx_orgao VARCHAR(60) NOT NULL,
    tx_setor VARCHAR(60),
    tx_numero_portaria VARCHAR(30) NOT NULL,
    dt_portaria DATE NOT NULL,
    nr_bca INTEGER NOT NULL,
    dt_bca DATE NOT NULL,
    url_pdf VARCHAR(500) NOT NULL,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_portaria_publicacao_documento_id ON t_portaria_publicacao(documento_id);

-- ── Anexos ─────────────────────────────────────────────────────────────────

CREATE TABLE t_anexo (
    id_anexo     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento (id_documento),
    nr_ordem     INTEGER NOT NULL,
    tx_titulo    VARCHAR(255) NOT NULL,
    url_imagem   VARCHAR(255) NOT NULL,
    dt_criacao   TIMESTAMP
);

-- ── Busca full-text ────────────────────────────────────────────────────────
-- unaccent combinado ao stemmer 'portuguese' (config própria) para que
-- "publicacao" (sem acento) ache "publicação" -- ver docs/funcionalidades.md.
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TEXT SEARCH CONFIGURATION portuguese_unaccent (COPY = portuguese);
ALTER TEXT SEARCH CONFIGURATION portuguese_unaccent
    ALTER MAPPING FOR hword, hword_part, word WITH unaccent, portuguese_stem;

-- ── Itens do documento (preliminar, normativa, final) ────────────────────────
-- As três tabelas compartilham a mesma forma (herdada de um mesmo conceito de
-- "item de conteúdo"); t_item_parte_normativa é a única com auto-referência
-- (parent_id) para representar a árvore de capítulos/seções/artigos/etc., e a
-- única com fl_incluido_emenda (marca de numeração com sufixo de letra, ex.
-- "Art. 5-A", permanente e independente do status de emenda ao vivo).
--
-- tsv_busca é uma coluna GERADA (STORED): o Postgres recalcula sozinho a cada
-- INSERT/UPDATE, indexando tx_titulo_item + tx_conteudo_completo (texto puro,
-- mantido por *Service.gerarFullTextContent) -- NUNCA tx_conteudo_item, que
-- guarda o JSON bruto do TipTap (ver collab/server.js), não texto pesquisável.

CREATE TABLE t_portaria (
    id_portaria             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            BIGINT NOT NULL REFERENCES t_documento (id_documento),
    sg_tipo_item            VARCHAR(255) NOT NULL,
    nr_ordem                INTEGER,
    tx_titulo_item          TEXT,
    tx_conteudo_item        TEXT,
    tx_conteudo_completo    TEXT,
    st_emenda               VARCHAR(20),
    tx_conteudo_original    TEXT,
    tx_titulo_original      TEXT,
    tx_conteudo_emenda      TEXT,
    tx_titulo_emenda        TEXT,
    tx_justificativa_emenda TEXT,
    tx_clausula_emenda      TEXT,
    tx_clausula_emenda_anterior TEXT,
    dt_criacao              TIMESTAMP,
    dt_atualizacao          TIMESTAMP,
    tsv_busca tsvector GENERATED ALWAYS AS (
        to_tsvector('portuguese_unaccent', coalesce(tx_titulo_item, '') || ' ' || coalesce(tx_conteudo_completo, ''))
    ) STORED
);
CREATE INDEX idx_portaria_busca ON t_portaria USING GIN (tsv_busca);

CREATE TABLE t_item_parte_normativa (
    id_item                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            BIGINT NOT NULL REFERENCES t_documento (id_documento),
    parent_id               BIGINT REFERENCES t_item_parte_normativa (id_item),
    sg_tipo_item            VARCHAR(255) NOT NULL,
    nr_ordem                INTEGER,
    tx_titulo_item          TEXT,
    tx_conteudo_item        TEXT,
    tx_conteudo_completo    TEXT,
    st_emenda               VARCHAR(20),
    tx_conteudo_original    TEXT,
    tx_titulo_original      TEXT,
    tx_conteudo_emenda      TEXT,
    tx_titulo_emenda        TEXT,
    tx_justificativa_emenda TEXT,
    tx_clausula_emenda      TEXT,
    tx_clausula_emenda_anterior TEXT,
    fl_incluido_emenda      BOOLEAN NOT NULL DEFAULT false,
    dt_criacao              TIMESTAMP,
    dt_atualizacao          TIMESTAMP,
    tsv_busca tsvector GENERATED ALWAYS AS (
        to_tsvector('portuguese_unaccent', coalesce(tx_titulo_item, '') || ' ' || coalesce(tx_conteudo_completo, ''))
    ) STORED
);
CREATE INDEX idx_item_parte_normativa_busca ON t_item_parte_normativa USING GIN (tsv_busca);

CREATE TABLE t_item_parte_final (
    id_item                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id            BIGINT NOT NULL REFERENCES t_documento (id_documento),
    sg_tipo_item            VARCHAR(255) NOT NULL,
    nr_ordem                INTEGER,
    tx_titulo_item          TEXT,
    tx_conteudo_item        TEXT,
    tx_conteudo_completo    TEXT,
    st_emenda               VARCHAR(20),
    tx_conteudo_original    TEXT,
    tx_titulo_original      TEXT,
    tx_conteudo_emenda      TEXT,
    tx_titulo_emenda        TEXT,
    tx_justificativa_emenda TEXT,
    tx_clausula_emenda      TEXT,
    tx_clausula_emenda_anterior TEXT,
    dt_criacao              TIMESTAMP,
    dt_atualizacao          TIMESTAMP,
    tsv_busca tsvector GENERATED ALWAYS AS (
        to_tsvector('portuguese_unaccent', coalesce(tx_titulo_item, '') || ' ' || coalesce(tx_conteudo_completo, ''))
    ) STORED
);
CREATE INDEX idx_item_parte_final_busca ON t_item_parte_final USING GIN (tsv_busca);
