-- Comentários em linha: dúvida/objeção/sugestão sobre um elemento específico
-- (artigo, parágrafo, inciso...) sem editar o texto dele -- revisão assíncrona,
-- ao estilo de comentário de Pull Request. Deliberadamente fora do Yjs/Hocuspocus:
-- nunca toca tx_conteudo_item do elemento, é uma tabela relacional à parte, então
-- sobrevive independente de quem está editando o texto no momento (ver
-- docs/roadmap.md, item descartado de fila/setor -- só este pedaço foi mantido).
--
-- elemento_id não tem FK: o elemento pode estar em t_item_parte_normativa,
-- t_portaria ou t_item_parte_final dependendo de "secao" -- mesmo padrão sem FK
-- já usado em t_emenda_historico.elemento_id, pelo mesmo motivo (uma só coluna
-- não pode apontar pra três tabelas diferentes).
-- ON DELETE CASCADE em documento_id (não limpo explicitamente em
-- DocumentoService.delete() como as tabelas de item -- mesmo padrão já usado em
-- t_documento_compartilhamento): um comentário não tem valor nenhum fora do
-- documento em que foi feito, diferente de LogAuditoria/EmendaHistorico, que
-- deliberadamente sobrevivem à exclusão do documento (trilha/histórico).
CREATE TABLE t_comentario_elemento (
    id_comentario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id  BIGINT NOT NULL REFERENCES t_documento (id_documento) ON DELETE CASCADE,
    elemento_id   BIGINT NOT NULL,
    secao         VARCHAR(30) NOT NULL,
    autor_id      BIGINT NOT NULL REFERENCES t_usuario (id_usuario),
    tx_texto      TEXT NOT NULL,
    -- Resposta em thread dentro do mesmo comentário -- NULL = comentário raiz.
    parent_id     BIGINT REFERENCES t_comentario_elemento (id_comentario) ON DELETE CASCADE,
    fl_resolvido  BOOLEAN NOT NULL DEFAULT false,
    dt_criacao    TIMESTAMP NOT NULL DEFAULT now(),
    dt_resolucao  TIMESTAMP
);

CREATE INDEX idx_comentario_elemento_documento ON t_comentario_elemento (documento_id);
CREATE INDEX idx_comentario_elemento_elemento ON t_comentario_elemento (documento_id, elemento_id, secao);
