CREATE TABLE t_anexo (
    id_anexo     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento(id_documento),
    tx_titulo    TEXT   NOT NULL,
    url_imagem   TEXT   NOT NULL,
    nr_ordem     INTEGER NOT NULL DEFAULT 1,
    dt_criacao   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
