-- Organizações militares (OM)
CREATE TABLE t_organizacao_militar (
    id_organizacao_militar BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_organizacao_militar VARCHAR(255) NOT NULL,
    sg_organizacao_militar VARCHAR(20) NOT NULL UNIQUE,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_alteracao TIMESTAMP,
    nr_versao INTEGER NOT NULL DEFAULT 0
);

-- Usuários. nr_cpf é a chave de login (e o identificador usado para
-- compartilhar documentos com outra pessoa) -- ver DocumentoCompartilhamento.
-- Cada usuário pertence a exatamente uma OM (fl_ativo permite desativar
-- sem apagar o vínculo de autoria dos documentos já criados por ele).
CREATE TABLE t_usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario VARCHAR(255) NOT NULL,
    nr_cpf VARCHAR(11) NOT NULL UNIQUE,
    tx_senha_hash VARCHAR(255) NOT NULL,
    om_id BIGINT NOT NULL REFERENCES t_organizacao_militar(id_organizacao_militar),
    fl_ativo BOOLEAN NOT NULL DEFAULT true,
    fl_sistema BOOLEAN NOT NULL DEFAULT false,
    dt_criacao TIMESTAMP NOT NULL DEFAULT now(),
    dt_alteracao TIMESTAMP,
    nr_versao INTEGER NOT NULL DEFAULT 0
);

-- Papéis do usuário (REDATOR / APROVADOR / ADMIN) -- ver PapelEnum.java.
-- Todo usuário autenticado já tem as capacidades de REDATOR implicitamente
-- (é o perfil padrão); esta tabela só registra concessões ADICIONAIS
-- (APROVADOR, ADMIN) por cima do perfil base.
CREATE TABLE t_usuario_papel (
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    sg_papel VARCHAR(20) NOT NULL,
    PRIMARY KEY (usuario_id, sg_papel)
);

-- Coautores de um documento (compartilhamento). Dá direito de EDITAR e,
-- enquanto o documento estiver em RASCUNHO/MINUTA, de EXCLUIR -- ver
-- DocumentoAcessoService. Só o autor do documento pode compartilhar ou
-- remover um coautor.
CREATE TABLE t_documento_compartilhamento (
    id_compartilhamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento(id_documento) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    dt_compartilhamento TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (documento_id, usuario_id)
);

-- Presença de edição: heartbeat gravado pelo frontend enquanto o editor de
-- um documento está aberto (ver DocumentoPresencaService). Uma linha mais
-- antiga que alguns segundos é considerada "não está mais editando" --
-- consultada, nunca varrida por um job, para manter isso simples nesta fase.
CREATE TABLE t_documento_edicao_ativa (
    id_edicao_ativa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL REFERENCES t_documento(id_documento) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES t_usuario(id_usuario) ON DELETE CASCADE,
    dt_ultimo_heartbeat TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (documento_id, usuario_id)
);

-- Autoria e OM do documento. Entram nulas para não quebrar os documentos já
-- existentes; o backfill abaixo aponta todos para o usuário/OM "sistema"
-- antes de travar a constraint NOT NULL.
ALTER TABLE t_documento ADD COLUMN autor_id BIGINT REFERENCES t_usuario(id_usuario);
ALTER TABLE t_documento ADD COLUMN om_id BIGINT REFERENCES t_organizacao_militar(id_organizacao_militar);

-- OM e usuário "sistema" -- dono de todo documento pré-existente na
-- migração. Distinto do usuário administrativo padrão (ver
-- DataSeeder.java), que é uma conta de login real; este aqui nunca loga
-- (senha hash inutilizável, fl_ativo = false).
INSERT INTO t_organizacao_militar (nm_organizacao_militar, sg_organizacao_militar)
VALUES ('Organização Padrão do Sistema', 'SISTEMA');

INSERT INTO t_usuario (nm_usuario, nr_cpf, tx_senha_hash, om_id, fl_ativo, fl_sistema)
VALUES (
    'Usuário Sistema',
    '00000000000',
    '!',
    (SELECT id_organizacao_militar FROM t_organizacao_militar WHERE sg_organizacao_militar = 'SISTEMA'),
    false,
    true
);

UPDATE t_documento
SET autor_id = (SELECT id_usuario FROM t_usuario WHERE fl_sistema = true),
    om_id = (SELECT om_id FROM t_usuario WHERE fl_sistema = true)
WHERE autor_id IS NULL;

ALTER TABLE t_documento ALTER COLUMN autor_id SET NOT NULL;
ALTER TABLE t_documento ALTER COLUMN om_id SET NOT NULL;
